### ISSUE TITLE
Feature Request: Damaged Wall/Building

### ISSUE THREAD

**Issue by ilovehans10** [Zylleon/ExtraAlerts#3]
A new alert for if a wall or building in the home zone has been damaged would be nice. This would be helpful in zombieland playthroughs with fog of war when it is hard to know if you have areas where there damage. It can also just be helpful after attacks knowing if everything has been repaired or not.

**Comment by Zylleon** [comment]
Probably not a good fit for this mod. It isn't usually something that can be fixed immediately, and eventually your colonists will automatically fix it even if you do nothing.
